### ISSUE TITLE
supports prettier 2?

### ISSUE THREAD

**Issue by lougreenwood** [mikew/prettier_d_slim#1]
I noticed that my code is not being formatted according to prettier 2 defaults (formatted output is missing parenthesis around single arg arrow function args: `(thing) => true`. Then I noticed that compatibility is listed as being with prettier ^1.19.1

I'm wondering if the server fallback to built in prettier 1 fallback if prettier is used in the project locally, which explains why the code looks like prettier 1 formatted code?

**Comment by mikew** [comment]
Hm, admittedly I haven't tested this with Prettier 2, but the idea here is if your local repo has prettier installed, it only uses that version. It does have some defaults (https://github.com/mikew/prettier_d_slim/blob/e670d3aa5011f9a0457c10b6420e69eacf8a1381/src/linter.ts#L68-L90) but you can see there the default for `arrow-parens` is to avoid.

Does the repo you're experiencing this in have a prettier config in it?

**Comment by lougreenwood** [comment]
> Does the repo you're experiencing this in have a prettier config in it?

Yep, and if I add `arrowParens: always`, I get the expected prettier 2 behaviour.

Is there a reason for setting these defaults rather than falling back to the defaults used by prettier?

**Comment by mikew** [comment]
IIRC (it's been a bit since I wrote this, and don't use it anymore) it's because when you use the prettier API, you have to send it some config. It doesn't assume the defaults in that scenario.

Also, just in general, probably never the best idea to rely on defaults if it's something you actually care about.

**Comment by lougreenwood** [comment]
Maybe it changed in V2, but it seems that defaults will be used if no overrides are passed in:

> format is used to format text using Prettier. Options may be provided to override the defaults. Set options.parser according to the language you are formatting (see the list of available parsers).

https://prettier.io/docs/en/api.html#prettierchecksource--options

And here, it's suggested to control options using a config file, so it's consistent across tooling:
> If you change any options, it’s recommended to do it via a configuration file. This way the Prettier CLI, editor integrations and other tooling knows what options you use.

https://prettier.io/docs/en/options.html

So it seems that perhaps it could be worth trying to strip away all of the non-essential options added in `linter.ts` - WDYT?

---

> Also, just in general, probably never the best idea to rely on defaults if it's something you actually care about.

My opinion is that is Prettier's job. I don't care about the defaults, only consistency of formatting. I leave Prettier to handle and "crowdsource" good / sane defaults on my behalf 😉.

**Comment by lougreenwood** [comment]
@mikew thanks for handling this! Seems that 1.1.0 isn't available on NPM, do you need to publish?

**Comment by MagicDuck** [comment]
hmm, yeah publishing the new version would be helpful...

**Comment by MagicDuck** [comment]
Published here in the meanwhile:
https://classic.yarnpkg.com/en/package/prettier_d_slim_latest
