### ISSUE TITLE
version is not reported correctly

### ISSUE THREAD

**Issue by lougreenwood** [mikew/prettier_d_slim#2]
when running `prettier_d_slim`, the reported version is incorrect, since it reports the bundled fallback version, not the project version which the server discovers, which is what I would expect to see reported.

(Also, there's a typo in the code to report the version... [this line](https://github.com/mikew/prettier_d_slim/blob/master/src/bin/prettier_d_slim.ts#L17) should be `require('../../package.json').version`)

**Comment by mikew** [comment]
This is an artifact from when I copied stuff from eslint_d. Really not a high priority, and if you'd like to do a PR, I'd suggest removing the prettier version and just report the one from this project.
